<?php
// ==========================================================================
// MELCOM AUDIT SYSTEM - STANDALONE MST_DEPT MANUAL SYNC & QUERY BUILDER
// Location: c:\Users\USER\Workspaces\htdocs\Melcom Mobile\scratch\manual_mst_dept_sync.php
// Use this script on the audit laptop or server where connection is active.
// ==========================================================================

error_reporting(E_ALL);
ini_set('display_errors', 1);

// --------------------------------------------------------------------------
// SECTION 1: RAW SQL QUERIES FOR DIRECT DATABASE TOOLS (Toad, SQLDeveloper, PL/SQL Developer)
// --------------------------------------------------------------------------
/*
-- IF YOUR MST_DEPT TABLE STORES INDIVIDUAL CODES/ITEMS (E.G. DEPT_CODE, VC_GROUP_CODE, VC_SUB_GROUP_CODE):

-- A. TRUNCATE THE LOCAL TABLE
TRUNCATE TABLE SHOP.MST_DEPT;

-- B. INSERT CORRESPONDING CATEGORY CODES FROM REMOTE VS_ITEM_AUDIT VIEW BASED ON SELECTED NAMES
INSERT INTO SHOP.MST_DEPT (
    DEPT_CODE, 
    VC_GROUP_CODE, 
    VC_SUB_GROUP_CODE
)
SELECT DISTINCT 
    TRIM(DEPT_CODE), 
    TRIM(VC_GROUP_CODE), 
    TRIM(VC_SUB_GROUP_CODE)
FROM VS_ITEM_AUDIT@DB_LINK_SHOP
WHERE DEPT_CODE IS NOT NULL 
  AND VC_GROUP_CODE IS NOT NULL 
  AND VC_SUB_GROUP_CODE IS NOT NULL
  AND TRIM(DEPT) IN ('SUPERMARKET') -- Replace with your selected department descriptions
  AND TRIM(GROUPS) IN ('PROVISIONS', 'TOILETRIES') -- Replace with your selected group descriptions
  AND TRIM(SUB_GROUP) IN ('MILK', 'SOAP'); -- Replace with your selected subgroup descriptions

COMMIT;


-- IF YOUR MST_DEPT TABLE STORES FULL ITEM SPECIFICATIONS (ITEM_CODE, ITEM_NAME, BARCODE, PRICE, ETC.):

-- A. TRUNCATE THE LOCAL TABLE
TRUNCATE TABLE SHOP.MST_DEPT;

-- B. BULK-COPY SELECTED ITEMS FROM REMOTE VIEW
INSERT INTO SHOP.MST_DEPT (
    ITEM_CODE, 
    ITEM_NAME, 
    BARCODE, 
    PRICE, 
    DEPT_CODE, 
    VC_GROUP_CODE, 
    VC_SUB_GROUP_CODE
)
SELECT DISTINCT 
    TRIM(ITEM_CODE), 
    TRIM(ITEM_NAME), 
    TRIM(BARCODE), 
    PRICE, 
    TRIM(DEPT_CODE), 
    TRIM(VC_GROUP_CODE), 
    TRIM(VC_SUB_GROUP_CODE)
FROM VS_ITEM_AUDIT@DB_LINK_SHOP
WHERE TRIM(DEPT) IN ('SUPERMARKET') -- Selected departments
  AND TRIM(GROUPS) IN ('PROVISIONS') -- Selected groups
  AND TRIM(SUB_GROUP) IN ('MILK'); -- Selected subgroups

COMMIT;
*/

// --------------------------------------------------------------------------
// SECTION 2: STANDALONE PHP UTILITY CODE (Run this directly via CLI or Browser)
// --------------------------------------------------------------------------
echo "==========================================================================\n";
echo "MELCOM STOCK SETUP: LOCAL MST_DEPT SYNCHRONIZATION TOOL\n";
echo "==========================================================================\n\n";

// Local database credentials
$db_host = "localhost";
$db_port = "1521";
$db_service = "orcl"; // or "xe"
$db_user = "SHOP";
$db_pass = "SHOP";

$tns = "(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = $db_host)(PORT = $db_port))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = $db_service)
    )
  )";

echo "[-] Connecting to local database at $db_host:$db_port/$db_service...\n";
$conn = @oci_connect($db_user, $db_pass, $tns);

if (!$conn) {
    $e = oci_error();
    echo "[!] Connection failed: " . $e['message'] . "\n";
    echo "[!] Ensure this script is run on the AUDIT LAPTOP or SERVER with connection privileges.\n";
    exit(1);
}
echo "[+] Connected successfully to local schema!\n\n";

// 1. Inspect local table column names
echo "[-] Inspecting schema columns of local 'MST_DEPT'...\n";
$col_query = "SELECT COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLS WHERE UPPER(TABLE_NAME) = 'MST_DEPT' ORDER BY COLUMN_ID";
$col_stmt = oci_parse($conn, $col_query);
$columns = [];
if ($col_stmt && @oci_execute($col_stmt)) {
    while ($row = oci_fetch_array($col_stmt, OCI_ASSOC)) {
        $columns[strtoupper($row['COLUMN_NAME'])] = $row['DATA_TYPE'];
    }
}
if ($col_stmt) oci_free_statement($col_stmt);

if (empty($columns)) {
    echo "[!] Table 'MST_DEPT' does not exist in local schema. Creating standard setup structure...\n";
    $create_sql = "
        CREATE TABLE SHOP.MST_DEPT (
            MST_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            SETUP_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            STOCK_DATE DATE,
            SHOP_CODE VARCHAR2(50),
            AUDIT_TYPE VARCHAR2(50),
            AUDIT_MODE VARCHAR2(100),
            SELECTED_DEPTS CLOB,
            SELECTED_GROUPS CLOB,
            SELECTED_SUBGROUPS CLOB,
            MAIL VARCHAR2(100),
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
        )
    ";
    $create_stmt = oci_parse($conn, $create_sql);
    if ($create_stmt && @oci_execute($create_stmt)) {
        echo "[+] Table 'MST_DEPT' created successfully!\n";
        // Re-read columns
        $col_stmt = oci_parse($conn, $col_query);
        if ($col_stmt && @oci_execute($col_stmt)) {
            while ($row = oci_fetch_array($col_stmt, OCI_ASSOC)) {
                $columns[strtoupper($row['COLUMN_NAME'])] = $row['DATA_TYPE'];
            }
        }
        if ($col_stmt) oci_free_statement($col_stmt);
    } else {
        $e = oci_error($create_stmt);
        echo "[!] Table creation failed: " . $e['message'] . "\n";
        exit(1);
    }
}

echo "[+] Columns found in MST_DEPT: " . implode(', ', array_keys($columns)) . "\n\n";

// 2. Define Scope filters (descriptions from UI)
// EDIT THESE VALUE LISTS TO REFLECT YOUR TARGET SCOPE TEST:
$selected_departments = ['SUPERMARKET'];
$selected_groups = ['PROVISIONS', 'TOILETRIES'];
$selected_subgroups = ['MILK', 'SOAP', 'SHAMPOO'];

echo "[-] Target Scope Filter Configured:\n";
echo "    Departments : " . implode(', ', $selected_departments) . "\n";
echo "    Groups      : " . implode(', ', $selected_groups) . "\n";
echo "    Subgroups   : " . implode(', ', $selected_subgroups) . "\n\n";

// 3. Clear/Truncate local table
echo "[-] Truncating table MST_DEPT...\n";
$trunc_stmt = @oci_parse($conn, "TRUNCATE TABLE SHOP.MST_DEPT");
$trunc_ok = @oci_execute($trunc_stmt);
if ($trunc_stmt) oci_free_statement($trunc_stmt);

if (!$trunc_ok) {
    echo "[-] Truncate failed (privilege restriction). Falling back to DELETE...\n";
    $del_stmt = oci_parse($conn, "DELETE FROM SHOP.MST_DEPT");
    oci_execute($del_stmt);
    if ($del_stmt) oci_free_statement($del_stmt);
}
echo "[+] MST_DEPT cleared successfully.\n\n";

// 4. Populate table using VS_ITEM_AUDIT@DB_LINK_SHOP remote view
$has_item_columns = isset($columns['ITEM_CODE']) || isset($columns['DEPT_CODE']) || isset($columns['VC_GROUP_CODE']) || isset($columns['VC_SUB_GROUP_CODE']);

if ($has_item_columns) {
    echo "[-] Building custom INSERT SELECT statement mapping local schema to remote view...\n";
    
    // Mappings from local columns to remote select expressions
    $supported_mappings = [
        'ITEM_CODE' => 'TRIM(ITEM_CODE)',
        'ITEM_NAME' => 'TRIM(ITEM_NAME)',
        'BARCODE' => 'TRIM(BARCODE)',
        'PRICE' => 'PRICE',
        'DT_EFFECT_DATE' => 'DT_EFFECT_DATE',
        'DEPT' => 'TRIM(DEPT)',
        'DEPT_CODE' => 'TRIM(DEPT_CODE)',
        'GROUPS' => 'TRIM(GROUPS)',
        'VC_GROUP_CODE' => 'TRIM(VC_GROUP_CODE)',
        'VC_GROUP' => 'TRIM(VC_GROUP_CODE)',
        'SUB_GROUP' => 'TRIM(SUB_GROUP)',
        'VC_SUB_GROUP_CODE' => 'TRIM(VC_SUB_GROUP_CODE)',
        'VC_SUBGROUP' => 'TRIM(VC_SUB_GROUP_CODE)',
        'PACK_SIZE' => 'PACK_SIZE',
        'CH_PI' => 'CH_PI',
        'CH_STATUS' => 'CH_STATUS',
        'VC_UNIT' => 'VC_UNIT'
    ];

    $insert_cols = [];
    $select_exprs = [];

    foreach ($columns as $colName => $colType) {
        if (isset($supported_mappings[$colName])) {
            $insert_cols[] = $colName;
            $select_exprs[] = $supported_mappings[$colName];
        }
    }

    if (!empty($insert_cols)) {
        $insert_str = implode(', ', $insert_cols);
        $select_str = implode(', ', $select_exprs);

        // Build dynamic bind query
        $select_query = "SELECT DISTINCT $select_str FROM VS_ITEM_AUDIT@DB_LINK_SHOP";
        $where_clauses = [];
        $binds = [];

        if (!empty($selected_departments)) {
            $phs = [];
            for ($i = 0; $i < count($selected_departments); $i++) {
                $phs[] = ':dept' . $i;
                $binds[':dept' . $i] = $selected_departments[$i];
            }
            $where_clauses[] = "TRIM(DEPT) IN (" . implode(', ', $phs) . ")";
        }

        if (!empty($selected_groups)) {
            $phs = [];
            for ($i = 0; $i < count($selected_groups); $i++) {
                $phs[] = ':grp' . $i;
                $binds[':grp' . $i] = $selected_groups[$i];
            }
            $where_clauses[] = "TRIM(GROUPS) IN (" . implode(', ', $phs) . ")";
        }

        if (!empty($selected_subgroups)) {
            $phs = [];
            for ($i = 0; $i < count($selected_subgroups); $i++) {
                $phs[] = ':sub' . $i;
                $binds[':sub' . $i] = $selected_subgroups[$i];
            }
            $where_clauses[] = "TRIM(SUB_GROUP) IN (" . implode(', ', $phs) . ")";
        }

        if (!empty($where_clauses)) {
            $select_query .= " WHERE " . implode(' AND ', $where_clauses);
        }

        $final_query = "INSERT INTO SHOP.MST_DEPT ($insert_str) $select_query";
        echo "[-] EXECUTING QUERY:\n$final_query\n\n";

        $stmt = oci_parse($conn, $final_query);
        foreach ($binds as $placeholder => $val) {
            oci_bind_by_name($stmt, $placeholder, $binds[$placeholder]);
        }

        $exec = @oci_execute($stmt);
        if ($exec) {
            $rows_inserted = oci_num_rows($stmt);
            echo "[+] Successful! Inserted $rows_inserted matching item records into local MST_DEPT!\n";
        } else {
            $e = oci_error($stmt);
            echo "[!] SQL execution error: " . $e['message'] . "\n";
        }
        if ($stmt) oci_free_statement($stmt);
    } else {
        echo "[!] No matching insert columns mapped. Check table definition.\n";
    }
} else {
    // Stores standard setup row
    echo "[-] Local MST_DEPT table represents a parameters configuration sheet. Inserting scope parameter row...\n";
    $insertQuery = "
        INSERT INTO SHOP.MST_DEPT (
            STOCK_DATE, SHOP_CODE, AUDIT_TYPE, AUDIT_MODE, SELECTED_DEPTS, SELECTED_GROUPS, SELECTED_SUBGROUPS, MAIL
        ) VALUES (
            SYSDATE, 'SC001', 'SST', 'ITEMWISE', :depts, :groups, :subgroups, 'auditor@melcom.com'
        )
    ";

    $stmt = oci_parse($conn, $insertQuery);
    $depts_str = implode(', ', $selected_departments);
    $groups_str = implode(', ', $selected_groups);
    $subgroups_str = implode(', ', $selected_subgroups);
    oci_bind_by_name($stmt, ':depts', $depts_str);
    oci_bind_by_name($stmt, ':groups', $groups_str);
    oci_bind_by_name($stmt, ':subgroups', $subgroups_str);

    if (@oci_execute($stmt)) {
        echo "[+] Setup parameters row successfully registered in MST_DEPT.\n";
    } else {
        $e = oci_error($stmt);
        echo "[!] Failed to insert parameters: " . $e['message'] . "\n";
    }
    oci_free_statement($stmt);
}

// Commit connection
$commit_stmt = oci_parse($conn, "COMMIT");
oci_execute($commit_stmt);
oci_free_statement($commit_stmt);

echo "\n[-] Closing active Oracle connection...\n";
oci_close($conn);
echo "[+] Completed successfully!\n";
echo "==========================================================================\n";
?>
